version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_LNDG_IP
      APP_PORT: $APP_LNDG_PORT

  web:
    image: ghcr.io/cryptosharks131/lndg:v1.6.3@sha256:1de4c2fa831c6deb4655c509ff9e32a29a349f77965304a8236da523b44ad8c1
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/root/.lnd:ro
      - ${APP_DATA_DIR}:/lndg/data
    command:
      - sh
      - -c
      - python initialize.py -net '${APP_BITCOIN_NETWORK}' -server '${APP_LIGHTNING_NODE_IP}:${APP_LIGHTNING_NODE_GRPC_PORT}' -pw '${APP_PASSWORD}' -d && supervisord && python manage.py runserver 0.0.0.0:${APP_LNDG_PORT}
    networks:
      default:
        ipv4_address: ${APP_LNDG_IP}
